# Generated by Django 5.2.17 on 2026-09-09 01:08

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.CharField(max_length=80, verbose_name='Формат сайта')),
                ('name', models.CharField(max_length=160, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('brief', models.FileField(blank=True, storage=pages.models.private_brief_storage, upload_to=pages.models.brief_path, verbose_name='Техническое задание')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('source_url', models.CharField(blank=True, max_length=300, verbose_name='Страница отправки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заявка на сайт',
                'verbose_name_plural': 'Заявки на сайты',
                'ordering': ('-created_at',),
            },
        ),
    ]
