# Generated by Django 5.2.16 on 2026-07-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('source_url', models.URLField(blank=True)),
                ('raw_text', models.TextField()),
                ('client_hint', models.CharField(blank=True, max_length=160)),
                ('budget_hint', models.CharField(blank=True, max_length=120)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.CharField(blank=True, max_length=80)),
                ('ai_notes', models.TextField(blank=True)),
                ('draft_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На просмотр'), ('sent_to_max', 'Отправлена в MAX'), ('skipped', 'Не подходит')], default='new', max_length=20)),
                ('max_status', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
