# Generated by Django 5.2.16 on 2026-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profi_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilead',
            name='source_url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
